services:
  - type: web
    name: photosorter
    env: python
    buildCommand: |
      echo "Installing Python dependencies..."
      pip install -r requirements.txt
      echo "Build completed - using static files"
    startCommand: |
      echo "Starting PhotoSorter application..."
      echo "Current directory: $(pwd)"
      echo "Starting GPS extraction server in background..."
      python3 gps-extractor.py 8088 &
      echo "Starting web server..."
      python3 -m http.server $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: CI
        value: false
    healthCheckPath: /photoSorter-simple.html
