services:
  - type: web
    name: photosorter
    env: python
    buildCommand: |
      echo "Starting PhotoSorter build process..."
      echo "Installing Python dependencies..."
      pip install -r requirements.txt
      echo "Python dependencies installed"
      echo "Installing Node.js dependencies..."
      cd frontend && npm install
      echo "Node dependencies installed"
      echo "Building frontend..."
      cd frontend && npm run build
      echo "Frontend build completed"
      echo "Copying frontend build to public directory..."
      cp -r frontend/build/* frontend/public/
      echo "Build process completed successfully"
    startCommand: |
      echo "Starting PhotoSorter application..."
      cd frontend/public
      echo "Current directory: $(pwd)"
      echo "Starting GPS extraction server in background..."
      python3 gps-extractor.py 8088 &
      echo "Starting web server..."
      python3 -m http.server $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: NODE_VERSION
        value: 18
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
    healthCheckPath: /photoSorter-simple.html
